Add option "-s"

diff --git a/bin/vcollect b/bin/vcollect
--- a/bin/vcollect
+++ b/bin/vcollect
@@ -43,6 +43,10 @@ function check_event_list_valid {
     event_list=$1
 }
 
+function check_perf_stream_valid {
+    perf_out_stream=$1
+}
+
 function check_cpu_architecure_valid {
     local t_architecture_name="${1^^}"
 
@@ -101,6 +105,8 @@ Options:
 
   --perf-binary PERF_LOCATION - location of perf
 
+  -s PERF_OUT_STREAM - perf output stream number
+
   -h - Displays this help message
 
 Actions:
@@ -128,6 +134,7 @@ repeat=1
 perf_exec=perf
 output_filename="perf.out"
 processor_architecture="OTHER"
+perf_out_stream=""
 
 show_help=""
 
@@ -182,7 +189,16 @@ while [[ ! -z "$1" ]]; do
 
             check_cpu_architecure_valid $arg
             ;;
-        "--perf-binary")
+        "-s" )
+            shift; arg="$1"
+            if [[ -z "$arg" ]] || [[ "$arg" =~ ^- ]]; then
+                echo "$usage"
+                exit 1
+            fi
+
+            check_perf_stream_valid $arg
+            ;;
+         "--perf-binary")
             shift; arg="$1"
             check_args_left $arg
 
@@ -194,6 +210,13 @@ while [[ ! -z "$1" ]]; do
             fi
             ;;
         * )
+            if [[ "$arg" =~ ^- ]]; then
+                echo -e "\nERROR: Invalid option ${arg}\n"
+
+                echo "$usage"
+                exit 1
+            fi
+
             # Read remaining arguments as the command
             exec_command=$@
             shift $#
@@ -237,20 +260,19 @@ function collect_data {
         exit 1
     fi
 
-    local temp_file=perf_test.out
-    $perf_exec stat -e cycles dd if=/dev/zero of=/dev/null count=100 1> $temp_file 0>&2 2> /dev/null
+    # Try to auto detect perf out stream if not specified
+    if [ -z "$perf_out_stream" ]; then
 
-    if [ -s $temp_file ]; then
-        perf_out_stream=1
-    else
-        $perf_exec stat -e cycles dd if=/dev/zero of=/dev/null count=100 2> $temp_file 0>&1 1> /dev/null
+        local temp_file=perf_test.out
+        $perf_exec stat -e cycles dd if=/dev/zero of=/dev/null count=100 1> $temp_file 0>&2 2> /dev/null
+
         if [ -s $temp_file ]; then
-            perf_out_stream=2
+            perf_out_stream=1
         else
-            perf_out_stream=0
+            perf_out_stream=2
         fi
+        rm $temp_file
     fi
-    rm $temp_file
 
     echo "Data collection started"
     echo -e "# Output file generated using $me \n#" > $output_filename
